version: '3'
services:
  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
        SAGA_TEST_VERSION: ${SAGA_TEST_VERSION:-9.12}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
