name: Test plugin

on:
  push:
    paths:
    - "processing_saga_nextgen/**"
    - ".github/workflows/test_plugin.yaml"
    - ".docker/**"
  pull_request:
    types: [opened, synchronize, edited]

env:
  # plugin name/directory where the code for the plugin is stored
  PLUGIN_NAME: processing_saga_nextgen
  # python notation to test running inside plugin
  TESTS_RUN_FUNCTION: processing_saga_nextgen.test_suite.test_package
  # Docker settings
  DOCKER_IMAGE: qgis/qgis


jobs:

  Test-plugin:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        qgis_version: ["3.40", "3.42", "4.2"]
    env:
      QGIS_TEST_VERSION: ${{ matrix.qgis_version }}
      SAGA_TEST_VERSION: "9.12"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test on QGIS
        run: docker compose -f .docker/docker-compose.gh.yml run qgis /usr/src/.docker/run-docker-tests.sh
